### PR TITLE
Implement unsubscribe

### PR DESCRIPTION
**Pull request by gtfierro**
Needs @jhkolb signoff on how much of the bookkeeping is necessary inside the unsubscribe method. The implementation seems to work okay in my initial tests

### CODE REVIEW

**Comment by jhkolb** [comment]
I've taken a look at everything,and obviously all of the new code looks reasonable.

I think everything should be okay on the bookkepping front as well, since the `_readFrame` function should handle unsubscribing just fine and will clean up the necessary state.

This all assumes I still understand Bosswave semantics properly. An unsubscription should prompt the agent to receive a frame with the corresponding sequence number and a key `finished` with value `true`, right?

Once that's confirmed, I can merge this in.

**Comment by gtfierro** [comment]
That's my understanding too, so I think we're ok.[Here's usub in the oob spec](https://github.com/immesys/bw2/blob/dev/doc/oob.md#usub---unsubscribe)

**Review by jhkolb — APPROVED** [review]

**Comment by jhkolb** [comment]
Cool, let's merge it in.

**Comment by gtfierro** [comment]
Thanks! Can you push the latest to pip? Should be `0.6.1`

**Comment by jhkolb** [comment]
Sure! I'm traveling today but will get to it when I can.

**Comment by jhkolb** [comment]
Should be done now.

**Pull request merged**
